sudo: required
dist: trusty

language: go

services:
  - docker

go:
  - 1.8

addons:
  hosts:
    - vault.localhost

script:
  - make create_test_services
  - sudo add-apt-repository ppa:masterminds/glide --yes && sudo apt-get update -y
  - sudo apt-get install glide -y
  - glide install
  - make test
  - make build
