version: build-{build}.{branch}
image: Visual Studio 2017
clone_folder: C:\gopath\src\github.com\nebtex\menshend
shallow_clone: true

hosts:
  vault.localhost: 127.0.0.1

environment:
  GOPATH: C:\gopath

platform:
  - x64

build: off

install:
  - go version
  - go env
  - ps: Start-FileDownload 'https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip'
  - 7z e glide-v0.12.3-windows-amd64.zip -y
  - curl -fsSL -o vault.zip https://releases.hashicorp.com/vault/0.7.0/vault_0.7.0_windows_amd64.zip
  - 7z e vault.zip -y
  - ps: $VaultProcess = Start-Process vault -ArgumentList 'server','-dev','-dev-root-token-id=myroot' -PassThru

on_finish:
  - ps: Stop-Process -Id $VaultProcess.Id

test_script:
  - set VAULT_ADDR=http://localhost:8200
  - set VAULT_TOKEN=myroot
  - set SESSION_SECRET=d59e18b46eb24c5ca57b20925acba47a
  - vault auth-enable userpass
  - vault auth-enable github
  - vault write auth/userpass/users/menshend password=test ttl=72h
  - glide install
  - go get github.com/rakyll/statik
  - ls C:\gopath\bin
  - rm -rf statik
  - C:\gopath\bin\statik.exe -src=ui
  - move C:\gopath\src\github.com\nebtex\menshend\index_appvenyor.go.tmpl C:\gopath\src\github.com\nebtex\menshend\statik\index.go
  - go test -v ./cmd/menshend
  - go test -v ./pkg/apis/menshend/v1
  - go test -v ./pkg/config
  - go test -v ./pkg/filters
  - go test -v ./pkg/pfclient
  - go test -v ./pkg/pfclient/chisel/client
  - go test -v ./pkg/pfclient/chisel/server
  - go test -v ./pkg/resolvers
  - go test -v ./pkg/resolvers/cache
  - go test -v ./pkg/strategy
  - go test -v ./pkg/utils
  - go test -v ./pkg/utils/test

deploy: off
