/* 
 * menshend-api
 *
 * The API for the Menshend Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// vault secret object
type Secret struct {

	RequestId string `json:"request_id,omitempty"`

	LeaseDuration int32 `json:"lease_duration,omitempty"`

	Renewable bool `json:"renewable,omitempty"`

	Data interface{} `json:"data,omitempty"`

	Warnings []string `json:"warnings,omitempty"`

	WrapInfo SecretWrapInfo `json:"wrap_info,omitempty"`

	Auth SecretAuth `json:"auth,omitempty"`
}
